### ISSUE TITLE
Cannot see build definition selection in Configuration

### ISSUE THREAD

**Issue by leonids2005** [sdavis3/CodeCoverageDashboardWidgets#35] opened 2020-05-11 15:45 UTC
The only Tile, Width, and Height are shown in Configuraiton

**Comment by sdavis3** [comment] 2020-05-11 16:26
@leonids2005, can you please attach a screenshot of what you are seeing?

**Comment by leonids2005** [comment] 2020-05-11 19:44
Actually, there is a second widget from you in the markeplace - and I can
select build definition there.

**Comment by leonids2005** [comment] 2020-05-11 19:50
strange, but now everything works ok.  But believe me when I first
installed it I could select build definition and other controls.

**Comment by sdavis3** [comment] 2020-05-11 20:03
@leonids2005 a second widget in the marketplace? Can you share a link to it? There shouldn't be a second widget in there.

**Comment by jvanzella** [comment] 2020-05-21 22:31
I am having the same problem, there is no way for me to configure the build I want to use.

![image](https://user-images.githubusercontent.com/2285857/82612633-2d808680-9b78-11ea-9f16-ff55022feb9d.png)

**Comment by jvanzella** [comment] 2020-05-21 22:33
And as for 2 in the marketplace, here they are

![image](https://user-images.githubusercontent.com/2285857/82612729-6f113180-9b78-11ea-9ddb-dea3cc1bda05.png)

**Comment by rofehaim** [comment] 2020-05-26 07:37
I'm having the same problem.. there is no option to choose build definition, only Width & Height
![image](https://user-images.githubusercontent.com/10534113/82873230-dc3c1280-9f3c-11ea-848a-fa8d4c3a6497.png)

**Comment by sdavis3** [comment] 2020-05-26 19:25
@rofehaim & @jvanzella Did this just start or has it been this way since you installed the widget? I'm attempting to reproduce.

**Comment by jvanzella** [comment] 2020-05-27 20:12
This was my first install.  I can't identify them, but one of the Widgets works in the store works, and one of them doesn't.  See my first image.

**Comment by sdavis3** [comment] 2020-05-27 20:54
Yes, I suspect it’s the other one or they are conflicting. I’m trying to get the clone removed from the marketplace. Uninstall both widgets and then go back and reinstall mine. It’s at the following url: https://marketplace.visualstudio.com/items?itemName=shanebdavis.code-coverage-dashboard-widgets

**Comment by rofehaim** [comment] 2020-06-02 06:32
I uninstalled the extension and reinstall it from your link but still the same behavior, I just have Hight and Width to choose..

**Comment by sdavis3** [comment] 2020-06-03 18:37
I'm unable to reproduce this issue with my extension. I do plan to release a new version soon with some additional features and I want to be sure I'm capturing any bug fixes related to this issue if I can.

With the rouge copy cat extension now removed, please uninstall the version you have currently installed and reinstall with the Code Coverage Widgets by Shane Davis.

**Comment by rofehaim** [comment] 2020-06-10 09:06
Ok, I reinstalled it and look like the issue was fixed.. Thanks!

**Comment by sdavis3** [comment] 2020-06-11 00:33
Excellent! I will close this item. Thank you for responding!

**Closed by sdavis3** 2020-06-11 00:33 UTC
Labels: investigating
